import maplibregl from "maplibre-gl";
import "maplibre-gl/dist/maplibre-gl.css";

const initialCenter = [139.766966, 35.681163];
const initailZoom = 14;
const map = new maplibregl.Map({
  container: "map",
  zoom: initailZoom,
  hash: true,
  center: initialCenter,
  minZoom: 0,
  maxZoom: 21,
  style: "styles/gsi_std.json",
  attributionControl: false,
});

window.map = map;

map.on("load", async () => {
  map.addControl(new maplibregl.NavigationControl());
  map.showTileBoundaries = true;
  map.on("move", () => {
    const center = map.getCenter();
    document.getElementById("fly").value =
      center.lat.toFixed(6) +
      ", " +
      center.lng.toFixed(6) +
      ", " +
      map.getZoom().toFixed(2);
  });
  // === レイヤグループ定義（style.jsonのレイヤIDに合わせて適宜編集） ===
  const layerGroups = {
    boundary: [
      "gsibv-vectortile-layer-857",
      "gsibv-vectortile-layer-858",
      "gsibv-vectortile-layer-859",
      "gsibv-vectortile-layer-893",
      "gsibv-vectortile-layer-894",
      "gsibv-vectortile-layer-895",
      "gsibv-vectortile-layer-896",
      "gsibv-vectortile-layer-897",
    ],
    building: [
      "gsibv-vectortile-layer-1257",
      "gsibv-vectortile-layer-1258",
      "gsibv-vectortile-layer-1259",
      "gsibv-vectortile-layer-1260",
      "gsibv-vectortile-layer-1261",
      "gsibv-vectortile-layer-1262",
      "gsibv-vectortile-layer-1263",
      "gsibv-vectortile-layer-1264",
      "gsibv-vectortile-layer-1265",
      "gsibv-vectortile-layer-1266",
      "gsibv-vectortile-layer-871",
      "gsibv-vectortile-layer-872",
      "gsibv-vectortile-layer-873",
      "gsibv-vectortile-layer-874",
      "gsibv-vectortile-layer-875",
      "gsibv-vectortile-layer-876",
      "gsibv-vectortile-layer-877",
      "gsibv-vectortile-layer-878",
      "gsibv-vectortile-layer-879",
      "gsibv-vectortile-layer-880",
      "gsibv-vectortile-layer-881",
      "gsibv-vectortile-layer-882",
      "gsibv-vectortile-layer-883",
      "gsibv-vectortile-layer-884",
      "gsibv-vectortile-layer-885",
      "gsibv-vectortile-layer-886",
      "gsibv-vectortile-layer-887",
      "gsibv-vectortile-layer-888",
      "gsibv-vectortile-layer-889",
      "gsibv-vectortile-layer-890",
      "gsibv-vectortile-layer-891",
      "gsibv-vectortile-layer-892",
    ],
    coastline: [
      "gsibv-vectortile-layer-788",
      "gsibv-vectortile-layer-789",
      "gsibv-vectortile-layer-791",
      "gsibv-vectortile-layer-792",
      "gsibv-vectortile-layer-793",
      "gsibv-vectortile-layer-794",
      "gsibv-vectortile-layer-795",
    ],
    contour: [
      "gsibv-vectortile-layer-801",
      "gsibv-vectortile-layer-802",
      "gsibv-vectortile-layer-803",
      "gsibv-vectortile-layer-804",
      "gsibv-vectortile-layer-805",
      "gsibv-vectortile-layer-806",
      "gsibv-vectortile-layer-818",
      "gsibv-vectortile-layer-819",
      "gsibv-vectortile-layer-820",
      "gsibv-vectortile-layer-821",
      "gsibv-vectortile-layer-822",
      "gsibv-vectortile-layer-823",
    ],
    elevation: [
      "gsibv-vectortile-layer-1341",
      "gsibv-vectortile-layer-1342",
      "gsibv-vectortile-layer-1343",
      "gsibv-vectortile-layer-1344",
      "gsibv-vectortile-layer-1345",
      "gsibv-vectortile-layer-1346",
      "gsibv-vectortile-layer-1347",
      "gsibv-vectortile-layer-1348",
    ],
    label: [
      "gsibv-vectortile-layer-1304",
      "gsibv-vectortile-layer-1337",
      "gsibv-vectortile-layer-1367",
      "gsibv-vectortile-layer-1368",
      "gsibv-vectortile-layer-1369",
      "gsibv-vectortile-layer-1370",
      "gsibv-vectortile-layer-1371",
      "gsibv-vectortile-layer-1372",
      "gsibv-vectortile-layer-1373",
      "gsibv-vectortile-layer-1376",
      "gsibv-vectortile-layer-1377",
      "gsibv-vectortile-layer-1378",
      "gsibv-vectortile-layer-1379",
      "gsibv-vectortile-layer-1380",
      "gsibv-vectortile-layer-1381",
      "gsibv-vectortile-layer-1382",
      "gsibv-vectortile-layer-1383",
      "gsibv-vectortile-layer-1384",
      "gsibv-vectortile-layer-1385",
      "gsibv-vectortile-layer-1386",
      "gsibv-vectortile-layer-1387",
      "gsibv-vectortile-layer-1388",
      "gsibv-vectortile-layer-1389",
      "gsibv-vectortile-layer-1390",
      "gsibv-vectortile-layer-1391",
      "gsibv-vectortile-layer-1392",
      "gsibv-vectortile-layer-1393",
      "gsibv-vectortile-layer-1394",
      "gsibv-vectortile-layer-1395",
      "gsibv-vectortile-layer-1396",
      "gsibv-vectortile-layer-1397",
      "gsibv-vectortile-layer-1398",
      "gsibv-vectortile-layer-1399",
      "gsibv-vectortile-layer-1400",
      "gsibv-vectortile-layer-1401",
      "gsibv-vectortile-layer-1402",
      "gsibv-vectortile-layer-1403",
      "gsibv-vectortile-layer-1404",
      "gsibv-vectortile-layer-1405",
      "gsibv-vectortile-layer-1406",
      "gsibv-vectortile-layer-1407",
      "gsibv-vectortile-layer-1408",
      "gsibv-vectortile-layer-1409",
      "gsibv-vectortile-layer-1410",
      "gsibv-vectortile-layer-1411",
      "gsibv-vectortile-layer-1412",
      "gsibv-vectortile-layer-1413",
      "gsibv-vectortile-layer-1414",
      "gsibv-vectortile-layer-1415",
      "gsibv-vectortile-layer-1416",
      "gsibv-vectortile-layer-1417",
      "gsibv-vectortile-layer-1418",
      "gsibv-vectortile-layer-1419",
      "gsibv-vectortile-layer-1420",
      "gsibv-vectortile-layer-1421",
      "gsibv-vectortile-layer-1422",
      "gsibv-vectortile-layer-1423",
      "gsibv-vectortile-layer-1424",
      "gsibv-vectortile-layer-1425",
      "gsibv-vectortile-layer-1426",
      "gsibv-vectortile-layer-1427",
      "gsibv-vectortile-layer-1428",
      "gsibv-vectortile-layer-1429",
      "gsibv-vectortile-layer-1430",
      "gsibv-vectortile-layer-1431",
      "gsibv-vectortile-layer-1432",
      "gsibv-vectortile-layer-1433",
      "gsibv-vectortile-layer-1434",
      "gsibv-vectortile-layer-1435",
      "gsibv-vectortile-layer-1436",
      "gsibv-vectortile-layer-1437",
      "gsibv-vectortile-layer-1438",
      "gsibv-vectortile-layer-1439",
      "gsibv-vectortile-layer-1440",
      "gsibv-vectortile-layer-1441",
      "gsibv-vectortile-layer-1442",
      "gsibv-vectortile-layer-1443",
      "gsibv-vectortile-layer-1444",
      "gsibv-vectortile-layer-1445",
      "gsibv-vectortile-layer-1446",
      "gsibv-vectortile-layer-1447",
      "gsibv-vectortile-layer-1448",
      "gsibv-vectortile-layer-1449",
      "gsibv-vectortile-layer-1450",
      "gsibv-vectortile-layer-1451",
      "gsibv-vectortile-layer-1452",
      "gsibv-vectortile-layer-1453",
      "gsibv-vectortile-layer-1454",
      "gsibv-vectortile-layer-1455",
      "gsibv-vectortile-layer-1456",
      "gsibv-vectortile-layer-1457",
      "gsibv-vectortile-layer-1458",
      "gsibv-vectortile-layer-1459",
      "gsibv-vectortile-layer-1460",
      "gsibv-vectortile-layer-1461",
      "gsibv-vectortile-layer-1462",
      "gsibv-vectortile-layer-1463",
      "gsibv-vectortile-layer-1464",
      "gsibv-vectortile-layer-1465",
      "gsibv-vectortile-layer-1466",
      "gsibv-vectortile-layer-1467",
      "gsibv-vectortile-layer-1468",
      "gsibv-vectortile-layer-1469",
      "gsibv-vectortile-layer-1470",
      "gsibv-vectortile-layer-1471",
      "gsibv-vectortile-layer-1472",
      "gsibv-vectortile-layer-1473",
      "gsibv-vectortile-layer-1474",
      "gsibv-vectortile-layer-1475",
      "gsibv-vectortile-layer-1476",
      "gsibv-vectortile-layer-1477",
      "gsibv-vectortile-layer-1478",
      "gsibv-vectortile-layer-1479",
      "gsibv-vectortile-layer-1480",
      "gsibv-vectortile-layer-1481",
      "gsibv-vectortile-layer-1482",
      "gsibv-vectortile-layer-1483",
      "gsibv-vectortile-layer-1484",
      "gsibv-vectortile-layer-1485",
      "gsibv-vectortile-layer-1486",
      "gsibv-vectortile-layer-1487",
      "gsibv-vectortile-layer-1488",
      "gsibv-vectortile-layer-1489",
      "gsibv-vectortile-layer-1490",
      "gsibv-vectortile-layer-1491",
      "gsibv-vectortile-layer-1492",
      "gsibv-vectortile-layer-1493",
      "gsibv-vectortile-layer-1494",
      "gsibv-vectortile-layer-1495",
      "gsibv-vectortile-layer-1496",
      "gsibv-vectortile-layer-1497",
      "gsibv-vectortile-layer-1498",
      "gsibv-vectortile-layer-1499",
      "gsibv-vectortile-layer-1500",
      "gsibv-vectortile-layer-1501",
      "gsibv-vectortile-layer-1502",
      "gsibv-vectortile-layer-1503",
      "gsibv-vectortile-layer-1504",
      "gsibv-vectortile-layer-1505",
      "gsibv-vectortile-layer-1506",
      "gsibv-vectortile-layer-1507",
      "gsibv-vectortile-layer-1508",
      "gsibv-vectortile-layer-1509",
      "gsibv-vectortile-layer-1510",
      "gsibv-vectortile-layer-1511",
      "gsibv-vectortile-layer-1512",
      "gsibv-vectortile-layer-1513",
      "gsibv-vectortile-layer-1514",
      "gsibv-vectortile-layer-1515",
      "gsibv-vectortile-layer-1516",
      "gsibv-vectortile-layer-1517",
      "gsibv-vectortile-layer-1518",
      "gsibv-vectortile-layer-1519",
      "gsibv-vectortile-layer-1520",
      "gsibv-vectortile-layer-1521",
      "gsibv-vectortile-layer-1522",
      "gsibv-vectortile-layer-1523",
      "gsibv-vectortile-layer-1524",
      "gsibv-vectortile-layer-1525",
      "gsibv-vectortile-layer-1526",
      "gsibv-vectortile-layer-1527",
      "gsibv-vectortile-layer-1528",
      "gsibv-vectortile-layer-1529",
      "gsibv-vectortile-layer-1530",
      "gsibv-vectortile-layer-1531",
    ],
    lake: [
      "gsibv-vectortile-layer-770",
      "gsibv-vectortile-layer-771",
      "gsibv-vectortile-layer-773",
      "gsibv-vectortile-layer-774",
      "gsibv-vectortile-layer-775",
    ],
    landforma: [
      "gsibv-vectortile-layer-779",
      "gsibv-vectortile-layer-780",
      "gsibv-vectortile-layer-800",
      "gsibv-vectortile-layer-810",
      "gsibv-vectortile-layer-811",
    ],
    landforml: [
      "gsibv-vectortile-layer-769",
      "gsibv-vectortile-layer-796",
      "gsibv-vectortile-layer-797",
      "gsibv-vectortile-layer-798",
      "gsibv-vectortile-layer-799",
      "gsibv-vectortile-layer-808",
      "gsibv-vectortile-layer-809",
      "gsibv-vectortile-layer-813",
      "gsibv-vectortile-layer-814",
      "gsibv-vectortile-layer-815",
      "gsibv-vectortile-layer-816",
      "gsibv-vectortile-layer-817",
      "gsibv-vectortile-layer-860",
    ],
    landformp: [
      "gsibv-vectortile-layer-1270",
      "gsibv-vectortile-layer-1271",
      "gsibv-vectortile-layer-812",
    ],
    railway: [
      "gsibv-vectortile-layer-1000",
      "gsibv-vectortile-layer-1001",
      "gsibv-vectortile-layer-1002",
      "gsibv-vectortile-layer-1003",
      "gsibv-vectortile-layer-1004",
      "gsibv-vectortile-layer-1005",
      "gsibv-vectortile-layer-1006",
      "gsibv-vectortile-layer-1007",
      "gsibv-vectortile-layer-1008",
      "gsibv-vectortile-layer-1009",
      "gsibv-vectortile-layer-1010",
      "gsibv-vectortile-layer-1011",
      "gsibv-vectortile-layer-1012",
      "gsibv-vectortile-layer-1013",
      "gsibv-vectortile-layer-1014",
      "gsibv-vectortile-layer-1015",
      "gsibv-vectortile-layer-1055",
      "gsibv-vectortile-layer-1056",
      "gsibv-vectortile-layer-1057",
      "gsibv-vectortile-layer-1058",
      "gsibv-vectortile-layer-1059",
      "gsibv-vectortile-layer-1060",
      "gsibv-vectortile-layer-1061",
      "gsibv-vectortile-layer-1062",
      "gsibv-vectortile-layer-1063",
      "gsibv-vectortile-layer-1064",
      "gsibv-vectortile-layer-1065",
      "gsibv-vectortile-layer-1066",
      "gsibv-vectortile-layer-1067",
      "gsibv-vectortile-layer-1068",
      "gsibv-vectortile-layer-1069",
      "gsibv-vectortile-layer-1070",
      "gsibv-vectortile-layer-1071",
      "gsibv-vectortile-layer-1072",
      "gsibv-vectortile-layer-1073",
      "gsibv-vectortile-layer-1074",
      "gsibv-vectortile-layer-1075",
      "gsibv-vectortile-layer-1076",
      "gsibv-vectortile-layer-1164",
      "gsibv-vectortile-layer-1165",
      "gsibv-vectortile-layer-1166",
      "gsibv-vectortile-layer-1167",
      "gsibv-vectortile-layer-1168",
      "gsibv-vectortile-layer-1169",
      "gsibv-vectortile-layer-1170",
      "gsibv-vectortile-layer-1171",
      "gsibv-vectortile-layer-1172",
      "gsibv-vectortile-layer-1173",
      "gsibv-vectortile-layer-1174",
      "gsibv-vectortile-layer-1175",
      "gsibv-vectortile-layer-1176",
      "gsibv-vectortile-layer-1177",
      "gsibv-vectortile-layer-1178",
      "gsibv-vectortile-layer-1179",
      "gsibv-vectortile-layer-1180",
      "gsibv-vectortile-layer-1181",
      "gsibv-vectortile-layer-1182",
      "gsibv-vectortile-layer-1183",
      "gsibv-vectortile-layer-1184",
      "gsibv-vectortile-layer-1185",
      "gsibv-vectortile-layer-1186",
      "gsibv-vectortile-layer-1187",
      "gsibv-vectortile-layer-1188",
      "gsibv-vectortile-layer-1189",
      "gsibv-vectortile-layer-1190",
      "gsibv-vectortile-layer-1191",
      "gsibv-vectortile-layer-1192",
      "gsibv-vectortile-layer-1193",
      "gsibv-vectortile-layer-1194",
      "gsibv-vectortile-layer-1195",
      "gsibv-vectortile-layer-1196",
      "gsibv-vectortile-layer-1197",
      "gsibv-vectortile-layer-1198",
      "gsibv-vectortile-layer-1199",
      "gsibv-vectortile-layer-1200",
      "gsibv-vectortile-layer-1201",
      "gsibv-vectortile-layer-1230",
      "gsibv-vectortile-layer-1231",
      "gsibv-vectortile-layer-1232",
      "gsibv-vectortile-layer-1233",
      "gsibv-vectortile-layer-1234",
      "gsibv-vectortile-layer-1235",
      "gsibv-vectortile-layer-1236",
      "gsibv-vectortile-layer-1237",
      "gsibv-vectortile-layer-1238",
      "gsibv-vectortile-layer-1239",
      "gsibv-vectortile-layer-1240",
      "gsibv-vectortile-layer-1241",
      "gsibv-vectortile-layer-1242",
      "gsibv-vectortile-layer-1243",
      "gsibv-vectortile-layer-1253",
      "gsibv-vectortile-layer-1254",
      "gsibv-vectortile-layer-987",
      "gsibv-vectortile-layer-988",
      "gsibv-vectortile-layer-989",
      "gsibv-vectortile-layer-990",
      "gsibv-vectortile-layer-991",
      "gsibv-vectortile-layer-992",
      "gsibv-vectortile-layer-993",
      "gsibv-vectortile-layer-994",
      "gsibv-vectortile-layer-995",
      "gsibv-vectortile-layer-996",
      "gsibv-vectortile-layer-997",
      "gsibv-vectortile-layer-998",
      "gsibv-vectortile-layer-999",
    ],
    river: [
      "gsibv-vectortile-layer-1267",
      "gsibv-vectortile-layer-1268",
      "gsibv-vectortile-layer-1269",
      "gsibv-vectortile-layer-762",
      "gsibv-vectortile-layer-763",
      "gsibv-vectortile-layer-764",
      "gsibv-vectortile-layer-765",
      "gsibv-vectortile-layer-766",
      "gsibv-vectortile-layer-776",
      "gsibv-vectortile-layer-777",
      "gsibv-vectortile-layer-778",
      "gsibv-vectortile-layer-781",
      "gsibv-vectortile-layer-782",
      "gsibv-vectortile-layer-783",
      "gsibv-vectortile-layer-784",
      "gsibv-vectortile-layer-785",
      "gsibv-vectortile-layer-786",
      "gsibv-vectortile-layer-787",
    ],
    road: [
      "gsibv-vectortile-layer-1016",
      "gsibv-vectortile-layer-1017",
      "gsibv-vectortile-layer-1018",
      "gsibv-vectortile-layer-1019",
      "gsibv-vectortile-layer-1020",
      "gsibv-vectortile-layer-1021",
      "gsibv-vectortile-layer-1022",
      "gsibv-vectortile-layer-1023",
      "gsibv-vectortile-layer-1024",
      "gsibv-vectortile-layer-1025",
      "gsibv-vectortile-layer-1026",
      "gsibv-vectortile-layer-1027",
      "gsibv-vectortile-layer-1028",
      "gsibv-vectortile-layer-1029",
      "gsibv-vectortile-layer-1030",
      "gsibv-vectortile-layer-1031",
      "gsibv-vectortile-layer-1032",
      "gsibv-vectortile-layer-1033",
      "gsibv-vectortile-layer-1034",
      "gsibv-vectortile-layer-1035",
      "gsibv-vectortile-layer-1036",
      "gsibv-vectortile-layer-1037",
      "gsibv-vectortile-layer-1038",
      "gsibv-vectortile-layer-1039",
      "gsibv-vectortile-layer-1040",
      "gsibv-vectortile-layer-1041",
      "gsibv-vectortile-layer-1042",
      "gsibv-vectortile-layer-1043",
      "gsibv-vectortile-layer-1044",
      "gsibv-vectortile-layer-1045",
      "gsibv-vectortile-layer-1046",
      "gsibv-vectortile-layer-1047",
      "gsibv-vectortile-layer-1048",
      "gsibv-vectortile-layer-1049",
      "gsibv-vectortile-layer-1050",
      "gsibv-vectortile-layer-1051",
      "gsibv-vectortile-layer-1052",
      "gsibv-vectortile-layer-1053",
      "gsibv-vectortile-layer-1054",
      "gsibv-vectortile-layer-1077",
      "gsibv-vectortile-layer-1078",
      "gsibv-vectortile-layer-1079",
      "gsibv-vectortile-layer-1080",
      "gsibv-vectortile-layer-1081",
      "gsibv-vectortile-layer-1082",
      "gsibv-vectortile-layer-1083",
      "gsibv-vectortile-layer-1084",
      "gsibv-vectortile-layer-1085",
      "gsibv-vectortile-layer-1086",
      "gsibv-vectortile-layer-1087",
      "gsibv-vectortile-layer-1088",
      "gsibv-vectortile-layer-1089",
      "gsibv-vectortile-layer-1090",
      "gsibv-vectortile-layer-1091",
      "gsibv-vectortile-layer-1092",
      "gsibv-vectortile-layer-1093",
      "gsibv-vectortile-layer-1094",
      "gsibv-vectortile-layer-1095",
      "gsibv-vectortile-layer-1096",
      "gsibv-vectortile-layer-1097",
      "gsibv-vectortile-layer-1098",
      "gsibv-vectortile-layer-1099",
      "gsibv-vectortile-layer-1100",
      "gsibv-vectortile-layer-1101",
      "gsibv-vectortile-layer-1102",
      "gsibv-vectortile-layer-1103",
      "gsibv-vectortile-layer-1104",
      "gsibv-vectortile-layer-1105",
      "gsibv-vectortile-layer-1106",
      "gsibv-vectortile-layer-1107",
      "gsibv-vectortile-layer-1108",
      "gsibv-vectortile-layer-1109",
      "gsibv-vectortile-layer-1110",
      "gsibv-vectortile-layer-1111",
      "gsibv-vectortile-layer-1112",
      "gsibv-vectortile-layer-1113",
      "gsibv-vectortile-layer-1114",
      "gsibv-vectortile-layer-1115",
      "gsibv-vectortile-layer-1116",
      "gsibv-vectortile-layer-1117",
      "gsibv-vectortile-layer-1118",
      "gsibv-vectortile-layer-1119",
      "gsibv-vectortile-layer-1120",
      "gsibv-vectortile-layer-1121",
      "gsibv-vectortile-layer-1122",
      "gsibv-vectortile-layer-1123",
      "gsibv-vectortile-layer-1124",
      "gsibv-vectortile-layer-1125",
      "gsibv-vectortile-layer-1126",
      "gsibv-vectortile-layer-1127",
      "gsibv-vectortile-layer-1128",
      "gsibv-vectortile-layer-1129",
      "gsibv-vectortile-layer-1130",
      "gsibv-vectortile-layer-1131",
      "gsibv-vectortile-layer-1132",
      "gsibv-vectortile-layer-1133",
      "gsibv-vectortile-layer-1134",
      "gsibv-vectortile-layer-1135",
      "gsibv-vectortile-layer-1136",
      "gsibv-vectortile-layer-1137",
      "gsibv-vectortile-layer-1138",
      "gsibv-vectortile-layer-1139",
      "gsibv-vectortile-layer-1140",
      "gsibv-vectortile-layer-1141",
      "gsibv-vectortile-layer-1142",
      "gsibv-vectortile-layer-1143",
      "gsibv-vectortile-layer-1144",
      "gsibv-vectortile-layer-1145",
      "gsibv-vectortile-layer-1146",
      "gsibv-vectortile-layer-1147",
      "gsibv-vectortile-layer-1148",
      "gsibv-vectortile-layer-1149",
      "gsibv-vectortile-layer-1150",
      "gsibv-vectortile-layer-1151",
      "gsibv-vectortile-layer-1152",
      "gsibv-vectortile-layer-1153",
      "gsibv-vectortile-layer-1154",
      "gsibv-vectortile-layer-1155",
      "gsibv-vectortile-layer-1156",
      "gsibv-vectortile-layer-1157",
      "gsibv-vectortile-layer-1158",
      "gsibv-vectortile-layer-1159",
      "gsibv-vectortile-layer-1160",
      "gsibv-vectortile-layer-1161",
      "gsibv-vectortile-layer-1162",
      "gsibv-vectortile-layer-1163",
      "gsibv-vectortile-layer-1202",
      "gsibv-vectortile-layer-1203",
      "gsibv-vectortile-layer-1204",
      "gsibv-vectortile-layer-1205",
      "gsibv-vectortile-layer-1206",
      "gsibv-vectortile-layer-1207",
      "gsibv-vectortile-layer-1208",
      "gsibv-vectortile-layer-1209",
      "gsibv-vectortile-layer-1210",
      "gsibv-vectortile-layer-1211",
      "gsibv-vectortile-layer-1212",
      "gsibv-vectortile-layer-1213",
      "gsibv-vectortile-layer-1214",
      "gsibv-vectortile-layer-1215",
      "gsibv-vectortile-layer-1216",
      "gsibv-vectortile-layer-1217",
      "gsibv-vectortile-layer-1218",
      "gsibv-vectortile-layer-1219",
      "gsibv-vectortile-layer-1220",
      "gsibv-vectortile-layer-1221",
      "gsibv-vectortile-layer-1222",
      "gsibv-vectortile-layer-1223",
      "gsibv-vectortile-layer-1224",
      "gsibv-vectortile-layer-1225",
      "gsibv-vectortile-layer-1226",
      "gsibv-vectortile-layer-1227",
      "gsibv-vectortile-layer-1228",
      "gsibv-vectortile-layer-1229",
      "gsibv-vectortile-layer-1244",
      "gsibv-vectortile-layer-1245",
      "gsibv-vectortile-layer-1246",
      "gsibv-vectortile-layer-1247",
      "gsibv-vectortile-layer-1248",
      "gsibv-vectortile-layer-1249",
      "gsibv-vectortile-layer-1250",
      "gsibv-vectortile-layer-1251",
      "gsibv-vectortile-layer-1252",
      "gsibv-vectortile-layer-1255",
      "gsibv-vectortile-layer-1256",
      "gsibv-vectortile-layer-898",
      "gsibv-vectortile-layer-899",
      "gsibv-vectortile-layer-900",
      "gsibv-vectortile-layer-901",
      "gsibv-vectortile-layer-902",
      "gsibv-vectortile-layer-903",
      "gsibv-vectortile-layer-904",
      "gsibv-vectortile-layer-905",
      "gsibv-vectortile-layer-906",
      "gsibv-vectortile-layer-907",
      "gsibv-vectortile-layer-908",
      "gsibv-vectortile-layer-909",
      "gsibv-vectortile-layer-910",
      "gsibv-vectortile-layer-911",
      "gsibv-vectortile-layer-912",
      "gsibv-vectortile-layer-913",
      "gsibv-vectortile-layer-914",
      "gsibv-vectortile-layer-915",
      "gsibv-vectortile-layer-916",
      "gsibv-vectortile-layer-917",
      "gsibv-vectortile-layer-918",
      "gsibv-vectortile-layer-919",
      "gsibv-vectortile-layer-920",
      "gsibv-vectortile-layer-921",
      "gsibv-vectortile-layer-922",
      "gsibv-vectortile-layer-923",
      "gsibv-vectortile-layer-924",
      "gsibv-vectortile-layer-925",
      "gsibv-vectortile-layer-926",
      "gsibv-vectortile-layer-927",
      "gsibv-vectortile-layer-928",
      "gsibv-vectortile-layer-929",
      "gsibv-vectortile-layer-930",
      "gsibv-vectortile-layer-931",
      "gsibv-vectortile-layer-932",
      "gsibv-vectortile-layer-933",
      "gsibv-vectortile-layer-934",
      "gsibv-vectortile-layer-935",
      "gsibv-vectortile-layer-936",
      "gsibv-vectortile-layer-937",
      "gsibv-vectortile-layer-938",
      "gsibv-vectortile-layer-939",
      "gsibv-vectortile-layer-940",
      "gsibv-vectortile-layer-941",
      "gsibv-vectortile-layer-942",
      "gsibv-vectortile-layer-943",
      "gsibv-vectortile-layer-944",
      "gsibv-vectortile-layer-945",
      "gsibv-vectortile-layer-946",
      "gsibv-vectortile-layer-947",
      "gsibv-vectortile-layer-948",
      "gsibv-vectortile-layer-949",
      "gsibv-vectortile-layer-950",
      "gsibv-vectortile-layer-951",
      "gsibv-vectortile-layer-952",
      "gsibv-vectortile-layer-953",
      "gsibv-vectortile-layer-954",
      "gsibv-vectortile-layer-955",
      "gsibv-vectortile-layer-956",
      "gsibv-vectortile-layer-957",
      "gsibv-vectortile-layer-958",
      "gsibv-vectortile-layer-959",
      "gsibv-vectortile-layer-960",
      "gsibv-vectortile-layer-961",
      "gsibv-vectortile-layer-962",
      "gsibv-vectortile-layer-963",
      "gsibv-vectortile-layer-964",
      "gsibv-vectortile-layer-965",
      "gsibv-vectortile-layer-966",
      "gsibv-vectortile-layer-967",
      "gsibv-vectortile-layer-968",
      "gsibv-vectortile-layer-969",
      "gsibv-vectortile-layer-970",
      "gsibv-vectortile-layer-971",
      "gsibv-vectortile-layer-972",
      "gsibv-vectortile-layer-973",
      "gsibv-vectortile-layer-974",
      "gsibv-vectortile-layer-975",
      "gsibv-vectortile-layer-976",
      "gsibv-vectortile-layer-977",
      "gsibv-vectortile-layer-978",
      "gsibv-vectortile-layer-979",
      "gsibv-vectortile-layer-980",
      "gsibv-vectortile-layer-981",
      "gsibv-vectortile-layer-982",
      "gsibv-vectortile-layer-983",
      "gsibv-vectortile-layer-984",
      "gsibv-vectortile-layer-985",
      "gsibv-vectortile-layer-986",
    ],
    searoute: [
      "gsibv-vectortile-layer-854",
      "gsibv-vectortile-layer-855",
      "gsibv-vectortile-layer-856",
    ],
    structurea: [
      "gsibv-vectortile-layer-832",
      "gsibv-vectortile-layer-833",
      "gsibv-vectortile-layer-834",
      "gsibv-vectortile-layer-835",
    ],
    structurel: [
      "gsibv-vectortile-layer-1272",
      "gsibv-vectortile-layer-1273",
      "gsibv-vectortile-layer-761",
      "gsibv-vectortile-layer-825",
      "gsibv-vectortile-layer-826",
      "gsibv-vectortile-layer-827",
      "gsibv-vectortile-layer-862",
      "gsibv-vectortile-layer-863",
      "gsibv-vectortile-layer-864",
      "gsibv-vectortile-layer-865",
      "gsibv-vectortile-layer-866",
      "gsibv-vectortile-layer-867",
      "gsibv-vectortile-layer-868",
      "gsibv-vectortile-layer-869",
      "gsibv-vectortile-layer-870",
    ],
    symbol: [
      "gsibv-vectortile-layer-1274",
      "gsibv-vectortile-layer-1275",
      "gsibv-vectortile-layer-1276",
      "gsibv-vectortile-layer-1277",
      "gsibv-vectortile-layer-1278",
      "gsibv-vectortile-layer-1279",
      "gsibv-vectortile-layer-1280",
      "gsibv-vectortile-layer-1281",
      "gsibv-vectortile-layer-1282",
      "gsibv-vectortile-layer-1283",
      "gsibv-vectortile-layer-1284",
      "gsibv-vectortile-layer-1285",
      "gsibv-vectortile-layer-1286",
      "gsibv-vectortile-layer-1287",
      "gsibv-vectortile-layer-1288",
      "gsibv-vectortile-layer-1289",
      "gsibv-vectortile-layer-1290",
      "gsibv-vectortile-layer-1291",
      "gsibv-vectortile-layer-1292",
      "gsibv-vectortile-layer-1293",
      "gsibv-vectortile-layer-1294",
      "gsibv-vectortile-layer-1295",
      "gsibv-vectortile-layer-1296",
      "gsibv-vectortile-layer-1297",
      "gsibv-vectortile-layer-1298",
      "gsibv-vectortile-layer-1299",
      "gsibv-vectortile-layer-1300",
      "gsibv-vectortile-layer-1301",
      "gsibv-vectortile-layer-1302",
      "gsibv-vectortile-layer-1303",
      "gsibv-vectortile-layer-1305",
      "gsibv-vectortile-layer-1306",
      "gsibv-vectortile-layer-1307",
      "gsibv-vectortile-layer-1308",
      "gsibv-vectortile-layer-1309",
      "gsibv-vectortile-layer-1310",
      "gsibv-vectortile-layer-1311",
      "gsibv-vectortile-layer-1312",
      "gsibv-vectortile-layer-1313",
      "gsibv-vectortile-layer-1314",
      "gsibv-vectortile-layer-1315",
      "gsibv-vectortile-layer-1316",
      "gsibv-vectortile-layer-1317",
      "gsibv-vectortile-layer-1318",
      "gsibv-vectortile-layer-1319",
      "gsibv-vectortile-layer-1320",
      "gsibv-vectortile-layer-1321",
      "gsibv-vectortile-layer-1322",
      "gsibv-vectortile-layer-1323",
      "gsibv-vectortile-layer-1324",
      "gsibv-vectortile-layer-1325",
      "gsibv-vectortile-layer-1326",
      "gsibv-vectortile-layer-1327",
      "gsibv-vectortile-layer-1328",
      "gsibv-vectortile-layer-1329",
      "gsibv-vectortile-layer-1330",
      "gsibv-vectortile-layer-1331",
      "gsibv-vectortile-layer-1332",
      "gsibv-vectortile-layer-1333",
      "gsibv-vectortile-layer-1334",
      "gsibv-vectortile-layer-1335",
      "gsibv-vectortile-layer-1336",
      "gsibv-vectortile-layer-1338",
      "gsibv-vectortile-layer-1339",
      "gsibv-vectortile-layer-1340",
      "gsibv-vectortile-layer-1361",
      "gsibv-vectortile-layer-1362",
      "gsibv-vectortile-layer-1363",
      "gsibv-vectortile-layer-1364",
      "gsibv-vectortile-layer-1365",
      "gsibv-vectortile-layer-1366",
      "gsibv-vectortile-layer-1374",
      "gsibv-vectortile-layer-1375",
      "gsibv-vectortile-layer-1532",
      "gsibv-vectortile-layer-1533",
      "gsibv-vectortile-layer-1534",
      "gsibv-vectortile-layer-1535",
      "gsibv-vectortile-layer-1536",
      "gsibv-vectortile-layer-1537",
      "gsibv-vectortile-layer-1538",
      "gsibv-vectortile-layer-836",
      "gsibv-vectortile-layer-837",
      "gsibv-vectortile-layer-838",
      "gsibv-vectortile-layer-839",
      "gsibv-vectortile-layer-840",
      "gsibv-vectortile-layer-841",
      "gsibv-vectortile-layer-842",
      "gsibv-vectortile-layer-843",
      "gsibv-vectortile-layer-844",
      "gsibv-vectortile-layer-845",
      "gsibv-vectortile-layer-846",
      "gsibv-vectortile-layer-847",
      "gsibv-vectortile-layer-848",
      "gsibv-vectortile-layer-849",
      "gsibv-vectortile-layer-850",
      "gsibv-vectortile-layer-851",
      "gsibv-vectortile-layer-852",
      "gsibv-vectortile-layer-853",
    ],
    transp: [
      "gsibv-vectortile-layer-1349",
      "gsibv-vectortile-layer-1350",
      "gsibv-vectortile-layer-1351",
      "gsibv-vectortile-layer-1352",
      "gsibv-vectortile-layer-1353",
      "gsibv-vectortile-layer-1354",
      "gsibv-vectortile-layer-1355",
      "gsibv-vectortile-layer-1356",
      "gsibv-vectortile-layer-1357",
      "gsibv-vectortile-layer-1358",
      "gsibv-vectortile-layer-1359",
      "gsibv-vectortile-layer-1360",
    ],
    waterarea: ["gsibv-vectortile-layer-767", "gsibv-vectortile-layer-768"],
    wstructurea: [
      "gsibv-vectortile-layer-828",
      "gsibv-vectortile-layer-829",
      "gsibv-vectortile-layer-830",
      "gsibv-vectortile-layer-831",
      "gsibv-vectortile-layer-861",
    ],
  };

  // === チェックボックスUI生成 ===
  const controlsContainer = document.getElementById("layer-controls");
  for (const [groupName, layerIds] of Object.entries(layerGroups)) {
    const label = document.createElement("label");
    label.style.display = "block";
    label.style.marginBottom = "5px";

    const checkbox = document.createElement("input");
    checkbox.type = "checkbox";
    checkbox.checked = true;
    checkbox.id = `toggle-${groupName}`;
    checkbox.dataset.group = groupName;

    const span = document.createElement("span");
    span.textContent = `${groupName}`;

    label.appendChild(checkbox);
    label.appendChild(span);
    controlsContainer.appendChild(label);
  }

  // === チェックボックスイベント処理 ===
  controlsContainer.addEventListener("change", (e) => {
    if (e.target.matches("input[type='checkbox']")) {
      const group = e.target.dataset.group;
      const visible = e.target.checked ? "visible" : "none";

      for (const layerId of layerGroups[group]) {
        if (map.getLayer(layerId)) {
          map.setLayoutProperty(layerId, "visibility", visible);
        }
      }
    }
  });
});

map.on("contextmenu", (e) => {
  const features = map.queryRenderedFeatures(e.point);
  resetHightlightLayers();

  if (features.length > 0) {
    console.log("フィーチャ数：" + features.length);
    for (let i = 0; i < features.length; i++) {
      const feature = features[i];
      console.log("レイヤーID：" + feature.layer.id);
      console.log("フィーチャID：" + feature.id);
      console.log(JSON.stringify(feature.properties, null, 2));
    }
    const lineFeatures = features.filter(
      (f) => "layer" in f && f.layer.type === "line"
    );
    if (lineFeatures.length > 0) {
      map.getSource("highlight-source-line").setData({
        type: "FeatureCollection",
        features: lineFeatures,
      });
    }
    const fillFeatures = features.filter(
      (f) => "layer" in f && f.layer.type === "fill" && f.layer.id !== "land"
    );
    if (fillFeatures.length > 0) {
      map.getSource("highlight-source-line").setData({
        type: "FeatureCollection",
        features: fillFeatures,
      });
    }
  }
  function resetHightlightLayers() {
    if (map.getSource("highlight-source-line")) {
      map.removeLayer("highlight-layer-line");
      map.removeSource("highlight-source-line");
    }
    map.addSource("highlight-source-line", {
      type: "geojson",
      data: {
        type: "FeatureCollection",
        features: [],
      },
    });
    map.addLayer({
      id: "highlight-layer-line",
      type: "line",
      source: "highlight-source-line",
      paint: {
        "line-color": "rgb(255, 0, 0)",
        "line-width": 2,
        "line-opacity": 0.8,
      },
    });
    if (map.getSource("highlight-source-fill")) {
      map.removeLayer("highlight-layer-fill");
      map.removeSource("highlight-source-fill");
    }
    map.addSource("highlight-source-fill", {
      type: "geojson",
      data: {
        type: "FeatureCollection",
        features: [],
      },
    });
    map.addLayer({
      id: "highlight-layer-fill",
      type: "fill",
      source: "highlight-source-fill",
      paint: {
        "fill-outline-color": "rgb(255, 0, 0)",
      },
    });
  }
});

document.getElementById("fly").value =
  initialCenter[1] + ", " + initialCenter[0] + ", " + initailZoom;

document.getElementById("fly").addEventListener("keypress", (e) => {
  if (e.key === "Enter") {
    var coords = document.getElementById("fly").value;
    var pattern = /^-?\d+(\.\d+)?,\s*-?\d+(\.\d+)?,\s\d+(\.\d+)?$/;
    if (pattern.test(coords)) {
      var splittedCoods = coords.split(",");
      map.jumpTo({
        center: [parseFloat(splittedCoods[1]), parseFloat(splittedCoods[0])],
        zoom: parseFloat(splittedCoods[2]),
      });
    }
  }
});
